branch-defaults:
  aws:
    environment: null
    group_suffix: null
  master:
    environment: production
global:
  application_name: uncorked
  branch: null
  default_ec2_keyname: uncorked
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
